version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Build started on `date` and $CODEBUILD_SRC_DIR
      - mvn install -DskipTests
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - echo copying jar file from .$CODEBUILD_SRC_DIR/target/patient-registration-0.0.1.jar to /home/ec2-user/server
      - cp .$CODEBUILD_SRC_DIR/target/patient-registration-0.0.1.jar ./home/ec2-user/server
artifacts:
  files:
    - scripts/*.sh
    - target/*.jar
    - appspec.yml
  discard-paths: yes
