version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/patient-registration-0.0.1-SNAPSHOT.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes